version: "3.8"
services:
  frontend:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
  
  backend:
    build: path/to/backend
    ports:
      - 8080:8080
    depends_on:
      - db
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  volumes:
    db:
    frontend:
    backend: