version: '3.8'

services:
  propertysmart-db:
    build: ./web/database
    volumes:
      - propertysmart-dbVolume:/var/lib/postgresql/data
    networks:
      - propertysmart-network

  propertysmart-backend:
    build: ./web/backend
    ports:
      - "8000:8000"
    depends_on:
      - propertysmart-db
    networks:
      - propertysmart-network

  propertysmart-frontend:
    build: ./web/frontend
    ports:
      - "3000:3000"
    depends_on:
      - propertysmart-backend
    networks:
      - propertysmart-network

volumes:
  propertysmart-dbVolume:

networks:
  propertysmart-network:
    driver: bridge
