ALTER TABLE "properties"
ALTER COLUMN "property_id" TYPE BIGINT,
ALTER COLUMN "beds" TYPE INT,
ALTER COLUMN "baths" TYPE INT,
ALTER COLUMN "parking" TYPE INT,
ALTER COLUMN "propertyType" TYPE VARCHAR(255),
ALTER COLUMN "propertyTypeFormatted" TYPE VARCHAR(255),
ALTER COLUMN "isRural" TYPE BOOLEAN,
ALTER COLUMN "landSize" TYPE INT,
ALTER COLUMN "landUnit" TYPE VARCHAR(255),
ALTER COLUMN "isRetirement" TYPE BOOLEAN,
ALTER COLUMN "street" TYPE VARCHAR(255),
ALTER COLUMN "suburb" TYPE VARCHAR(255),
ALTER COLUMN "state" TYPE VARCHAR(255)
ALTER COLUMN "postcode" TYPE VARCHAR(4),
ALTER COLUMN "lat" TYPE VARCHAR(255),
ALTER COLUMN "lng" TYPE VARCHAR(255),
ALTER COLUMN "price" TYPE BIGINT,
ALTER COLUMN "tagText" TYPE VARCHAR(255),
ALTER COLUMN "tagClassName" TYPE VARCHAR(255),
ALTER COLUMN "url" TYPE VARCHAR(255);

ALTER TABLE "properties"
ALTER COLUMN "soldDate" TYPE DATE USING "soldDate"::date;

ALTER TABLE "properties" ALTER COLUMN "soldDate" TYPE DATE USING "soldDate"::date;

ALTER TABLE properties DROP COLUMN location;
CREATE EXTENSION IF NOT EXISTS postgis;
ALTER TABLE properties ADD COLUMN location GEOGRAPHY(POINT, 4326);
UPDATE properties SET location = ST_MakePoint(CAST(lng AS FLOAT), CAST(lat AS FLOAT))::geography;
CREATE INDEX location_idx ON properties USING GIST(location);

