name: Build and deploy Node.js app to Azure Web App - propertysmart

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Setup .env File
        run: |
          echo "REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}" > ${{ github.workspace }}/web/frontend/.env
        env:
          REACT_APP_BACKEND_URL: 'https://propertysmart-backend.azurewebsites.net' # Set your backend URL here

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4916410A6892490AA5DCE255832FD690 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B13620B8E7C842E39233BC5D3C7D7830 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_01D3AECCF6FA40DB8229E4B01BEBAC42 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'propertysmart'
          slot-name: 'Production'
          package: .
          